# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6d5ef7fd0b6709d673acfb2af8b7fd3dea1219f4824dafae4703a7a55c90424708645681761db8ffb603813d7e08a4326ea98a996b4f4aef326c08c33633869

test:
  secret_key_base: da06b4d19106f9ab1c58d20b6a6e9d9f8626d22d4eb282355cdc42041bf1879511c77b805d705fd9c56aa2ac1f923c6fca40f2a8da68e1d699d1bdf03d857cb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
